name: Test building with various Apple SDK configurations

on:
  push:

jobs:
  macos:
    strategy:
      fail-fast: false
      matrix:
        include:
          - { runner: macos-12, version: 10.6 }
          - { runner: macos-12, version: 10.9 }
          - { runner: macos-12, version: 10.12 }
          - { runner: macos-12, version: 10.15 }
          - { runner: macos-14, version: 11.0 }
          - { runner: macos-14, version: 12.0 }
          - { runner: macos-14, version: 13.0 }
          - { runner: macos-14, version: 14.0 }
    runs-on: ${{matrix.runner}}
    steps:
      - name: Install prerequisites
        if: ${{matrix.runner == 'macos-12'}}
        run: |
          brew install nasm
      - uses: actions/checkout@v4
      - name: Build
        run: |
          mkdir build
          cd build
          ../configure --enable-gpl --extra-cflags="-mmacosx-version-min=${{matrix.version}}"
          make -j$(sysctl -n hw.ncpu)

  ios:
    strategy:
      fail-fast: false
      matrix:
        runner:
          - macos-14
        version:
          - 9.0
          - 12.0
          - 15.0
          - 17.0
    runs-on: ${{matrix.runner}}
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: |
          mkdir build
          cd build
          # TODO: --disable-outdev=audiotoolbox should not be needed
          ../configure --enable-gpl --enable-cross-compile --arch=arm64 --target-os=darwin --cc="clang -arch arm64 -miphoneos-version-min=${{matrix.version}} -isysroot $(xcrun --sdk iphoneos --show-sdk-path)" --disable-outdev=audiotoolbox
          make -j$(sysctl -n hw.ncpu)

  tvos:
    strategy:
      fail-fast: false
      matrix:
        runner:
          - macos-14
        version:
          - 9.0
          - 12.0
          - 15.0
          - 17.0
    runs-on: ${{matrix.runner}}
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: |
          mkdir build
          cd build
          ../configure --enable-gpl --enable-cross-compile --arch=arm64 --target-os=darwin --cc="clang -arch arm64 -mtvos-version-min=${{matrix.version}} -isysroot $(xcrun --sdk appletvos --show-sdk-path)"
          make -j$(sysctl -n hw.ncpu)
